

spring:
  datasource:
    name: demo
    jdbcUrl: jdbc:mysql://192.168.170.17:3306/springboot_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&transformedBitIsBoolean=true
    username: root
    password: test
    driverClassName: com.mysql.cj.jdbc.Driver
    filters: config,log4j,stat
    maxActive: 30
    initialSize: 2
    maxWait: 60000
    minIdle: 2
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 192.168.170.20
#    password:
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 4
        max-wait: -1ms
        min-idle: 2

convertlab:
  grantType: client_credentials
  appid: cl02da164630fdaaf
  secret: 3ea3fa9cea8e2e9d3d823848202f3ec52d008507
  tenantId: 1587

